os: unstable
environment:
  matrix:
    - nodejs_version: '11'
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm ci
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn run compile-win32
